# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"
    config.vm.synced_folder "~/Documents/FinalExam/servers/syn_folder", "/home/vagrant/synced_folder"

        config.vm.define "DataBase", autostart:true do |node|

            # 主机名
            node.vm.hostname="DataBase"
            # 设置虚拟机的私有IP
            node.vm.network "private_network", ip: "192.168.10.50"
            # 设置主机与虚拟机的共享目录
            
              # VirtaulBox相关配置
            node.vm.provider "virtualbox" do |v|
                # 设置虚拟机的名称
                v.name = "DataBase"
                # 设置虚拟机的内存大小
                v.memory = 512
                # 设置虚拟机的CPU个数
                v.cpus = 1
            end    
        end
end