Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"
    config.vm.synced_folder "~/Documents/FinalExam/servers/syn_folder", "/home/vagrant/synced_folder"

    config.vm.define "NagiosMonitor", autostart:true do |node|

        # 主机名
        node.vm.hostname="NagiosMonitor"
        # 设置虚拟机的私有IP
        node.vm.network "private_network", ip: "192.168.10.10"
        # 设置主机与虚拟机的共享目录
        
          # VirtaulBox相关配置
        node.vm.provider "virtualbox" do |v|
            # 设置虚拟机的名称
            v.name = "Nagios"
            # 设置虚拟机的内存大小
            v.memory = 512
            # 设置虚拟机的CPU个数
            v.cpus = 1
        end

    end
end